// Generated by kea-typegen on Sat, 03 Oct 2026 14:45:34 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { FeatureFlagsLogicProps } from './featureFlagsLogic'
import type { FeatureFlag } from './generated/models/index'

export interface featureFlagsLogicType extends Logic {
    actionCreators: {
        setSearch: (search: string) => ({
            type: "set search (products.featureFlags.featureFlagsLogic.*)";
            payload: {
                search: string;
            };
        });
        toggleFlagActive: (id: number, active: boolean) => ({
            type: "toggle flag active (products.featureFlags.featureFlagsLogic.*)";
            payload: {
                active: boolean;
                id: number;
            };
        });
        setMutationError: (error: string | null) => ({
            type: "set mutation error (products.featureFlags.featureFlagsLogic.*)";
            payload: {
                error: string | null;
            };
        });
        setLoadError: (error: string | null) => ({
            type: "set load error (products.featureFlags.featureFlagsLogic.*)";
            payload: {
                error: string | null;
            };
        });
        loadFeatureFlags: () => ({
            type: "load feature flags (products.featureFlags.featureFlagsLogic.*)";
            payload: any;
        });
        loadFeatureFlagsSuccess: (featureFlags: FeatureFlag[], payload?: any) => ({
            type: "load feature flags success (products.featureFlags.featureFlagsLogic.*)";
            payload: {
                featureFlags: FeatureFlag[];
                payload?: any;
            };
        });
        loadFeatureFlagsFailure: (error: string, errorObject?: any) => ({
            type: "load feature flags failure (products.featureFlags.featureFlagsLogic.*)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
    };
    actionKeys: {
        "set search (products.featureFlags.featureFlagsLogic.*)": "setSearch";
        "toggle flag active (products.featureFlags.featureFlagsLogic.*)": "toggleFlagActive";
        "set mutation error (products.featureFlags.featureFlagsLogic.*)": "setMutationError";
        "set load error (products.featureFlags.featureFlagsLogic.*)": "setLoadError";
        "load feature flags (products.featureFlags.featureFlagsLogic.*)": "loadFeatureFlags";
        "load feature flags success (products.featureFlags.featureFlagsLogic.*)": "loadFeatureFlagsSuccess";
        "load feature flags failure (products.featureFlags.featureFlagsLogic.*)": "loadFeatureFlagsFailure";
    };
    actionTypes: {
        setSearch: "set search (products.featureFlags.featureFlagsLogic.*)";
        toggleFlagActive: "toggle flag active (products.featureFlags.featureFlagsLogic.*)";
        setMutationError: "set mutation error (products.featureFlags.featureFlagsLogic.*)";
        setLoadError: "set load error (products.featureFlags.featureFlagsLogic.*)";
        loadFeatureFlags: "load feature flags (products.featureFlags.featureFlagsLogic.*)";
        loadFeatureFlagsSuccess: "load feature flags success (products.featureFlags.featureFlagsLogic.*)";
        loadFeatureFlagsFailure: "load feature flags failure (products.featureFlags.featureFlagsLogic.*)";
    };
    actions: {
        setSearch: (search: string) => void;
        toggleFlagActive: (id: number, active: boolean) => void;
        setMutationError: (error: string | null) => void;
        setLoadError: (error: string | null) => void;
        loadFeatureFlags: () => void;
        loadFeatureFlagsSuccess: (featureFlags: FeatureFlag[], payload?: any) => void;
        loadFeatureFlagsFailure: (error: string, errorObject?: any) => void;
    };
    asyncActions: {
        setSearch: (search: string) => Promise<any>;
        toggleFlagActive: (id: number, active: boolean) => Promise<any>;
        setMutationError: (error: string | null) => Promise<any>;
        setLoadError: (error: string | null) => Promise<any>;
        loadFeatureFlags: () => Promise<any>;
        loadFeatureFlagsSuccess: (featureFlags: FeatureFlag[], payload?: any) => Promise<any>;
        loadFeatureFlagsFailure: (error: string, errorObject?: any) => Promise<any>;
    };
    defaults: {
        search: string;
        mutationError: string | null;
        loadError: string | null;
        featureFlags: FeatureFlag[];
        featureFlagsLoading: boolean;
    };
    events: {};
    key: number;
    listeners: {
        "loadFeatureFlags": ((action: {
            type: "load feature flags (products.featureFlags.featureFlagsLogic.*)";
            payload: any;
        }, previousState: any) => void | Promise<void>)[];
        "loadFeatureFlagsFailure": ((action: {
            type: "load feature flags failure (products.featureFlags.featureFlagsLogic.*)";
            payload: {
                error: string;
                errorObject?: any;
            };
        }, previousState: any) => void | Promise<void>)[];
        "toggleFlagActive": ((action: {
            type: "toggle flag active (products.featureFlags.featureFlagsLogic.*)";
            payload: {
                active: boolean;
                id: number;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "products",
        "featureFlags",
        "featureFlagsLogic",
        "*"
    ];
    pathString: "products.featureFlags.featureFlagsLogic.*";
    props: FeatureFlagsLogicProps;
    reducer: (state: any, action: any, fullState: any) => {
        search: string;
        mutationError: string | null;
        loadError: string | null;
        featureFlags: FeatureFlag[];
        featureFlagsLoading: boolean;
    };
    reducers: {
        search: (state: string, action: any, fullState: any) => string;
        mutationError: (state: string | null, action: any, fullState: any) => string | null;
        loadError: (state: string | null, action: any, fullState: any) => string | null;
        featureFlags: (state: FeatureFlag[], action: any, fullState: any) => FeatureFlag[];
        featureFlagsLoading: (state: boolean, action: any, fullState: any) => boolean;
    };
    selector: (state: any) => {
        search: string;
        mutationError: string | null;
        loadError: string | null;
        featureFlags: FeatureFlag[];
        featureFlagsLoading: boolean;
    };
    selectors: {
        search: (state: any, props?: any) => string;
        mutationError: (state: any, props?: any) => string | null;
        loadError: (state: any, props?: any) => string | null;
        featureFlags: (state: any, props?: any) => FeatureFlag[];
        featureFlagsLoading: (state: any, props?: any) => boolean;
        filteredFlags: (state: any, props?: any) => FeatureFlag[];
    };
    sharedListeners: {};
    values: {
        search: string;
        mutationError: string | null;
        loadError: string | null;
        featureFlags: FeatureFlag[];
        featureFlagsLoading: boolean;
        filteredFlags: FeatureFlag[];
    };
    _isKea: true;
    _isKeaWithKey: true;
    __keaTypeGenInternalSelectorTypes: {
        filteredFlags: (featureFlags: FeatureFlag[], search: string) => FeatureFlag[];
    };
}