// Generated by kea-typegen on Sat, 03 Oct 2026 14:45:34 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { FeatureFlagLogicProps } from './featureFlagLogic'
import type { FeatureFlag } from './generated/models/index'
import type { FeatureFlagRequest } from './generated/models/featureFlagRequest'
import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'

export interface featureFlagLogicType extends Logic {
    actionCreators: {
        flagSaved: (flag: FeatureFlag) => ({
            type: "flag saved (products.featureFlags.featureFlagLogic.*)";
            payload: {
                flag: FeatureFlag;
            };
        });
        setSaveError: (error: string | null) => ({
            type: "set save error (products.featureFlags.featureFlagLogic.*)";
            payload: {
                error: string | null;
            };
        });
        setLoadError: (error: string | null) => ({
            type: "set load error (products.featureFlags.featureFlagLogic.*)";
            payload: {
                error: string | null;
            };
        });
        loadFeatureFlag: () => ({
            type: "load feature flag (products.featureFlags.featureFlagLogic.*)";
            payload: any;
        });
        loadFeatureFlagSuccess: (featureFlag: FeatureFlag | null, payload?: any) => ({
            type: "load feature flag success (products.featureFlags.featureFlagLogic.*)";
            payload: {
                featureFlag: FeatureFlag | null;
                payload?: any;
            };
        });
        loadFeatureFlagFailure: (error: string, errorObject?: any) => ({
            type: "load feature flag failure (products.featureFlags.featureFlagLogic.*)";
            payload: {
                error: string;
                errorObject?: any;
            };
        });
        setFlagFormValue: (key: FieldName, value: any) => ({
            type: "set flag form value (products.featureFlags.featureFlagLogic.*)";
            payload: {
                name: FieldName;
                value: any;
            };
        });
        setFlagFormValues: (values: DeepPartial<FeatureFlagRequest>) => ({
            type: "set flag form values (products.featureFlags.featureFlagLogic.*)";
            payload: {
                values: DeepPartial<FeatureFlagRequest>;
            };
        });
        setFlagFormManualErrors: (errors: Record<string, any>) => ({
            type: "set flag form manual errors (products.featureFlags.featureFlagLogic.*)";
            payload: {
                errors: Record<string, any>;
            };
        });
        touchFlagFormField: (key: string) => ({
            type: "touch flag form field (products.featureFlags.featureFlagLogic.*)";
            payload: {
                key: string;
            };
        });
        resetFlagForm: (values?: FeatureFlagRequest) => ({
            type: "reset flag form (products.featureFlags.featureFlagLogic.*)";
            payload: {
                values?: FeatureFlagRequest;
            };
        });
        submitFlagForm: () => ({
            type: "submit flag form (products.featureFlags.featureFlagLogic.*)";
            payload: {
                value: boolean;
            };
        });
        submitFlagFormRequest: (flagForm: FeatureFlagRequest) => ({
            type: "submit flag form request (products.featureFlags.featureFlagLogic.*)";
            payload: {
                flagForm: FeatureFlagRequest;
            };
        });
        submitFlagFormSuccess: (flagForm: FeatureFlagRequest) => ({
            type: "submit flag form success (products.featureFlags.featureFlagLogic.*)";
            payload: {
                flagForm: FeatureFlagRequest;
            };
        });
        submitFlagFormFailure: (error: Error, errors: Record<string, any>) => ({
            type: "submit flag form failure (products.featureFlags.featureFlagLogic.*)";
            payload: {
                error: Error;
                errors: Record<string, any>;
            };
        });
    };
    actionKeys: {
        "flag saved (products.featureFlags.featureFlagLogic.*)": "flagSaved";
        "set save error (products.featureFlags.featureFlagLogic.*)": "setSaveError";
        "set load error (products.featureFlags.featureFlagLogic.*)": "setLoadError";
        "load feature flag (products.featureFlags.featureFlagLogic.*)": "loadFeatureFlag";
        "load feature flag success (products.featureFlags.featureFlagLogic.*)": "loadFeatureFlagSuccess";
        "load feature flag failure (products.featureFlags.featureFlagLogic.*)": "loadFeatureFlagFailure";
        "set flag form value (products.featureFlags.featureFlagLogic.*)": "setFlagFormValue";
        "set flag form values (products.featureFlags.featureFlagLogic.*)": "setFlagFormValues";
        "set flag form manual errors (products.featureFlags.featureFlagLogic.*)": "setFlagFormManualErrors";
        "touch flag form field (products.featureFlags.featureFlagLogic.*)": "touchFlagFormField";
        "reset flag form (products.featureFlags.featureFlagLogic.*)": "resetFlagForm";
        "submit flag form (products.featureFlags.featureFlagLogic.*)": "submitFlagForm";
        "submit flag form request (products.featureFlags.featureFlagLogic.*)": "submitFlagFormRequest";
        "submit flag form success (products.featureFlags.featureFlagLogic.*)": "submitFlagFormSuccess";
        "submit flag form failure (products.featureFlags.featureFlagLogic.*)": "submitFlagFormFailure";
    };
    actionTypes: {
        flagSaved: "flag saved (products.featureFlags.featureFlagLogic.*)";
        setSaveError: "set save error (products.featureFlags.featureFlagLogic.*)";
        setLoadError: "set load error (products.featureFlags.featureFlagLogic.*)";
        loadFeatureFlag: "load feature flag (products.featureFlags.featureFlagLogic.*)";
        loadFeatureFlagSuccess: "load feature flag success (products.featureFlags.featureFlagLogic.*)";
        loadFeatureFlagFailure: "load feature flag failure (products.featureFlags.featureFlagLogic.*)";
        setFlagFormValue: "set flag form value (products.featureFlags.featureFlagLogic.*)";
        setFlagFormValues: "set flag form values (products.featureFlags.featureFlagLogic.*)";
        setFlagFormManualErrors: "set flag form manual errors (products.featureFlags.featureFlagLogic.*)";
        touchFlagFormField: "touch flag form field (products.featureFlags.featureFlagLogic.*)";
        resetFlagForm: "reset flag form (products.featureFlags.featureFlagLogic.*)";
        submitFlagForm: "submit flag form (products.featureFlags.featureFlagLogic.*)";
        submitFlagFormRequest: "submit flag form request (products.featureFlags.featureFlagLogic.*)";
        submitFlagFormSuccess: "submit flag form success (products.featureFlags.featureFlagLogic.*)";
        submitFlagFormFailure: "submit flag form failure (products.featureFlags.featureFlagLogic.*)";
    };
    actions: {
        flagSaved: (flag: FeatureFlag) => void;
        setSaveError: (error: string | null) => void;
        setLoadError: (error: string | null) => void;
        loadFeatureFlag: () => void;
        loadFeatureFlagSuccess: (featureFlag: FeatureFlag | null, payload?: any) => void;
        loadFeatureFlagFailure: (error: string, errorObject?: any) => void;
        setFlagFormValue: (key: FieldName, value: any) => void;
        setFlagFormValues: (values: DeepPartial<FeatureFlagRequest>) => void;
        setFlagFormManualErrors: (errors: Record<string, any>) => void;
        touchFlagFormField: (key: string) => void;
        resetFlagForm: (values?: FeatureFlagRequest) => void;
        submitFlagForm: () => void;
        submitFlagFormRequest: (flagForm: FeatureFlagRequest) => void;
        submitFlagFormSuccess: (flagForm: FeatureFlagRequest) => void;
        submitFlagFormFailure: (error: Error, errors: Record<string, any>) => void;
    };
    asyncActions: {
        flagSaved: (flag: FeatureFlag) => Promise<any>;
        setSaveError: (error: string | null) => Promise<any>;
        setLoadError: (error: string | null) => Promise<any>;
        loadFeatureFlag: () => Promise<any>;
        loadFeatureFlagSuccess: (featureFlag: FeatureFlag | null, payload?: any) => Promise<any>;
        loadFeatureFlagFailure: (error: string, errorObject?: any) => Promise<any>;
        setFlagFormValue: (key: FieldName, value: any) => Promise<any>;
        setFlagFormValues: (values: DeepPartial<FeatureFlagRequest>) => Promise<any>;
        setFlagFormManualErrors: (errors: Record<string, any>) => Promise<any>;
        touchFlagFormField: (key: string) => Promise<any>;
        resetFlagForm: (values?: FeatureFlagRequest) => Promise<any>;
        submitFlagForm: () => Promise<any>;
        submitFlagFormRequest: (flagForm: FeatureFlagRequest) => Promise<any>;
        submitFlagFormSuccess: (flagForm: FeatureFlagRequest) => Promise<any>;
        submitFlagFormFailure: (error: Error, errors: Record<string, any>) => Promise<any>;
    };
    defaults: {
        saveError: string | null;
        loadError: string | null;
        featureFlag: FeatureFlag | null;
        featureFlagLoading: boolean;
        flagForm: FeatureFlagRequest;
        isFlagFormSubmitting: boolean;
        showFlagFormErrors: boolean;
        flagFormChanged: boolean;
        flagFormTouches: Record<string, boolean>;
        flagFormManualErrors: Record<string, any>;
    };
    events: {};
    key: string;
    listeners: {
        "loadFeatureFlag": ((action: {
            type: "load feature flag (products.featureFlags.featureFlagLogic.*)";
            payload: any;
        }, previousState: any) => void | Promise<void>)[];
        "loadFeatureFlagFailure": ((action: {
            type: "load feature flag failure (products.featureFlags.featureFlagLogic.*)";
            payload: {
                error: string;
                errorObject?: any;
            };
        }, previousState: any) => void | Promise<void>)[];
        "loadFeatureFlagSuccess": ((action: {
            type: "load feature flag success (products.featureFlags.featureFlagLogic.*)";
            payload: {
                featureFlag: FeatureFlag | null;
                payload?: any;
            };
        }, previousState: any) => void | Promise<void>)[];
        "flagSaved": ((action: {
            type: "flag saved (products.featureFlags.featureFlagLogic.*)";
            payload: {
                flag: FeatureFlag;
            };
        }, previousState: any) => void | Promise<void>)[];
    };
    path: [
        "products",
        "featureFlags",
        "featureFlagLogic",
        "*"
    ];
    pathString: "products.featureFlags.featureFlagLogic.*";
    props: FeatureFlagLogicProps;
    reducer: (state: any, action: any, fullState: any) => {
        saveError: string | null;
        loadError: string | null;
        featureFlag: FeatureFlag | null;
        featureFlagLoading: boolean;
        flagForm: FeatureFlagRequest;
        isFlagFormSubmitting: boolean;
        showFlagFormErrors: boolean;
        flagFormChanged: boolean;
        flagFormTouches: Record<string, boolean>;
        flagFormManualErrors: Record<string, any>;
    };
    reducers: {
        saveError: (state: string | null, action: any, fullState: any) => string | null;
        loadError: (state: string | null, action: any, fullState: any) => string | null;
        featureFlag: (state: FeatureFlag | null, action: any, fullState: any) => FeatureFlag | null;
        featureFlagLoading: (state: boolean, action: any, fullState: any) => boolean;
        flagForm: (state: FeatureFlagRequest, action: any, fullState: any) => FeatureFlagRequest;
        isFlagFormSubmitting: (state: boolean, action: any, fullState: any) => boolean;
        showFlagFormErrors: (state: boolean, action: any, fullState: any) => boolean;
        flagFormChanged: (state: boolean, action: any, fullState: any) => boolean;
        flagFormTouches: (state: Record<string, boolean>, action: any, fullState: any) => Record<string, boolean>;
        flagFormManualErrors: (state: Record<string, any>, action: any, fullState: any) => Record<string, any>;
    };
    selector: (state: any) => {
        saveError: string | null;
        loadError: string | null;
        featureFlag: FeatureFlag | null;
        featureFlagLoading: boolean;
        flagForm: FeatureFlagRequest;
        isFlagFormSubmitting: boolean;
        showFlagFormErrors: boolean;
        flagFormChanged: boolean;
        flagFormTouches: Record<string, boolean>;
        flagFormManualErrors: Record<string, any>;
    };
    selectors: {
        saveError: (state: any, props?: any) => string | null;
        loadError: (state: any, props?: any) => string | null;
        featureFlag: (state: any, props?: any) => FeatureFlag | null;
        featureFlagLoading: (state: any, props?: any) => boolean;
        flagForm: (state: any, props?: any) => FeatureFlagRequest;
        isFlagFormSubmitting: (state: any, props?: any) => boolean;
        showFlagFormErrors: (state: any, props?: any) => boolean;
        flagFormChanged: (state: any, props?: any) => boolean;
        flagFormTouches: (state: any, props?: any) => Record<string, boolean>;
        flagFormManualErrors: (state: any, props?: any) => Record<string, any>;
        flagFormTouched: (state: any, props?: any) => boolean;
        flagFormValidationErrors: (state: any, props?: any) => DeepPartialMap<FeatureFlagRequest, ValidationErrorType>;
        flagFormAllErrors: (state: any, props?: any) => Record<string, any>;
        flagFormHasErrors: (state: any, props?: any) => boolean;
        flagFormErrors: (state: any, props?: any) => DeepPartialMap<FeatureFlagRequest, ValidationErrorType>;
        isFlagFormValid: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        saveError: string | null;
        loadError: string | null;
        featureFlag: FeatureFlag | null;
        featureFlagLoading: boolean;
        flagForm: FeatureFlagRequest;
        isFlagFormSubmitting: boolean;
        showFlagFormErrors: boolean;
        flagFormChanged: boolean;
        flagFormTouches: Record<string, boolean>;
        flagFormManualErrors: Record<string, any>;
        flagFormTouched: boolean;
        flagFormValidationErrors: DeepPartialMap<FeatureFlagRequest, ValidationErrorType>;
        flagFormAllErrors: Record<string, any>;
        flagFormHasErrors: boolean;
        flagFormErrors: DeepPartialMap<FeatureFlagRequest, ValidationErrorType>;
        isFlagFormValid: boolean;
    };
    _isKea: true;
    _isKeaWithKey: true;
}