// Generated by kea-typegen. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { RolloutPlanLogicProps } from './rolloutPlanLogic'
import type {
    ProjectsFeatureFlagsRolloutPlanDestroyParams,
    RolloutPlan,
    RolloutPlanMutationRequest,
} from './generated/models/index'

export interface rolloutPlanLogicType extends Logic {
    actionCreators: {
        setRolloutDraft: (draft: RolloutPlanMutationRequest) => {
            type: 'set rollout draft (products.featureFlags.rolloutPlanLogic.*)'
            payload: {
                draft: RolloutPlanMutationRequest
            }
        }
        setPlanError: (error: string | null) => {
            type: 'set plan error (products.featureFlags.rolloutPlanLogic.*)'
            payload: {
                error: string | null
            }
        }
        loadRolloutPlan: () => {
            type: 'load rollout plan (products.featureFlags.rolloutPlanLogic.*)'
            payload: any
        }
        loadRolloutPlanSuccess: (
            rolloutPlan: RolloutPlan | null,
            payload?: any
        ) => {
            type: 'load rollout plan success (products.featureFlags.rolloutPlanLogic.*)'
            payload: {
                rolloutPlan: RolloutPlan | null
                payload?: any
            }
        }
        loadRolloutPlanFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'load rollout plan failure (products.featureFlags.rolloutPlanLogic.*)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        saveRolloutPlan: (request: RolloutPlanMutationRequest) => {
            type: 'save rollout plan (products.featureFlags.rolloutPlanLogic.*)'
            payload: RolloutPlanMutationRequest
        }
        saveRolloutPlanSuccess: (
            rolloutPlan: RolloutPlan,
            payload?: RolloutPlanMutationRequest
        ) => {
            type: 'save rollout plan success (products.featureFlags.rolloutPlanLogic.*)'
            payload: {
                rolloutPlan: RolloutPlan
                payload?: RolloutPlanMutationRequest
            }
        }
        saveRolloutPlanFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'save rollout plan failure (products.featureFlags.rolloutPlanLogic.*)'
            payload: {
                error: string
                errorObject?: any
            }
        }
        deleteRolloutPlan: (request: ProjectsFeatureFlagsRolloutPlanDestroyParams) => {
            type: 'delete rollout plan (products.featureFlags.rolloutPlanLogic.*)'
            payload: ProjectsFeatureFlagsRolloutPlanDestroyParams
        }
        deleteRolloutPlanSuccess: (
            rolloutPlan: null,
            payload?: ProjectsFeatureFlagsRolloutPlanDestroyParams
        ) => {
            type: 'delete rollout plan success (products.featureFlags.rolloutPlanLogic.*)'
            payload: {
                rolloutPlan: null
                payload?: ProjectsFeatureFlagsRolloutPlanDestroyParams
            }
        }
        deleteRolloutPlanFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'delete rollout plan failure (products.featureFlags.rolloutPlanLogic.*)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'set rollout draft (products.featureFlags.rolloutPlanLogic.*)': 'setRolloutDraft'
        'set plan error (products.featureFlags.rolloutPlanLogic.*)': 'setPlanError'
        'load rollout plan (products.featureFlags.rolloutPlanLogic.*)': 'loadRolloutPlan'
        'load rollout plan success (products.featureFlags.rolloutPlanLogic.*)': 'loadRolloutPlanSuccess'
        'load rollout plan failure (products.featureFlags.rolloutPlanLogic.*)': 'loadRolloutPlanFailure'
        'save rollout plan (products.featureFlags.rolloutPlanLogic.*)': 'saveRolloutPlan'
        'save rollout plan success (products.featureFlags.rolloutPlanLogic.*)': 'saveRolloutPlanSuccess'
        'save rollout plan failure (products.featureFlags.rolloutPlanLogic.*)': 'saveRolloutPlanFailure'
        'delete rollout plan (products.featureFlags.rolloutPlanLogic.*)': 'deleteRolloutPlan'
        'delete rollout plan success (products.featureFlags.rolloutPlanLogic.*)': 'deleteRolloutPlanSuccess'
        'delete rollout plan failure (products.featureFlags.rolloutPlanLogic.*)': 'deleteRolloutPlanFailure'
    }
    actionTypes: {
        setRolloutDraft: 'set rollout draft (products.featureFlags.rolloutPlanLogic.*)'
        setPlanError: 'set plan error (products.featureFlags.rolloutPlanLogic.*)'
        loadRolloutPlan: 'load rollout plan (products.featureFlags.rolloutPlanLogic.*)'
        loadRolloutPlanSuccess: 'load rollout plan success (products.featureFlags.rolloutPlanLogic.*)'
        loadRolloutPlanFailure: 'load rollout plan failure (products.featureFlags.rolloutPlanLogic.*)'
        saveRolloutPlan: 'save rollout plan (products.featureFlags.rolloutPlanLogic.*)'
        saveRolloutPlanSuccess: 'save rollout plan success (products.featureFlags.rolloutPlanLogic.*)'
        saveRolloutPlanFailure: 'save rollout plan failure (products.featureFlags.rolloutPlanLogic.*)'
        deleteRolloutPlan: 'delete rollout plan (products.featureFlags.rolloutPlanLogic.*)'
        deleteRolloutPlanSuccess: 'delete rollout plan success (products.featureFlags.rolloutPlanLogic.*)'
        deleteRolloutPlanFailure: 'delete rollout plan failure (products.featureFlags.rolloutPlanLogic.*)'
    }
    actions: {
        setRolloutDraft: (draft: RolloutPlanMutationRequest) => void
        setPlanError: (error: string | null) => void
        loadRolloutPlan: () => void
        loadRolloutPlanSuccess: (rolloutPlan: RolloutPlan | null, payload?: any) => void
        loadRolloutPlanFailure: (error: string, errorObject?: any) => void
        saveRolloutPlan: (request: RolloutPlanMutationRequest) => void
        saveRolloutPlanSuccess: (rolloutPlan: RolloutPlan, payload?: RolloutPlanMutationRequest) => void
        saveRolloutPlanFailure: (error: string, errorObject?: any) => void
        deleteRolloutPlan: (request: ProjectsFeatureFlagsRolloutPlanDestroyParams) => void
        deleteRolloutPlanSuccess: (rolloutPlan: null, payload?: ProjectsFeatureFlagsRolloutPlanDestroyParams) => void
        deleteRolloutPlanFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        setRolloutDraft: (draft: RolloutPlanMutationRequest) => Promise<any>
        setPlanError: (error: string | null) => Promise<any>
        loadRolloutPlan: () => Promise<any>
        loadRolloutPlanSuccess: (rolloutPlan: RolloutPlan | null, payload?: any) => Promise<any>
        loadRolloutPlanFailure: (error: string, errorObject?: any) => Promise<any>
        saveRolloutPlan: (request: RolloutPlanMutationRequest) => Promise<any>
        saveRolloutPlanSuccess: (rolloutPlan: RolloutPlan, payload?: RolloutPlanMutationRequest) => Promise<any>
        saveRolloutPlanFailure: (error: string, errorObject?: any) => Promise<any>
        deleteRolloutPlan: (request: ProjectsFeatureFlagsRolloutPlanDestroyParams) => Promise<any>
        deleteRolloutPlanSuccess: (
            rolloutPlan: null,
            payload?: ProjectsFeatureFlagsRolloutPlanDestroyParams
        ) => Promise<any>
        deleteRolloutPlanFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        rolloutDraft: RolloutPlanMutationRequest
        planError: string | null
        rolloutPlan: RolloutPlan | null
        rolloutPlanLoading: boolean
    }
    events: {}
    key: string
    listeners: {
        loadRolloutPlan: ((
            action: {
                type: 'load rollout plan (products.featureFlags.rolloutPlanLogic.*)'
                payload: any
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadRolloutPlanSuccess: ((
            action: {
                type: 'load rollout plan success (products.featureFlags.rolloutPlanLogic.*)'
                payload: {
                    rolloutPlan: RolloutPlan | null
                    payload?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        loadRolloutPlanFailure: ((
            action: {
                type: 'load rollout plan failure (products.featureFlags.rolloutPlanLogic.*)'
                payload: {
                    error: string
                    errorObject?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        saveRolloutPlan: ((
            action: {
                type: 'save rollout plan (products.featureFlags.rolloutPlanLogic.*)'
                payload: RolloutPlanMutationRequest
            },
            previousState: any
        ) => void | Promise<void>)[]
        saveRolloutPlanSuccess: ((
            action: {
                type: 'save rollout plan success (products.featureFlags.rolloutPlanLogic.*)'
                payload: {
                    rolloutPlan: RolloutPlan
                    payload?: RolloutPlanMutationRequest
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        saveRolloutPlanFailure: ((
            action: {
                type: 'save rollout plan failure (products.featureFlags.rolloutPlanLogic.*)'
                payload: {
                    error: string
                    errorObject?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        deleteRolloutPlanSuccess: ((
            action: {
                type: 'delete rollout plan success (products.featureFlags.rolloutPlanLogic.*)'
                payload: {
                    rolloutPlan: null
                    payload?: ProjectsFeatureFlagsRolloutPlanDestroyParams
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        deleteRolloutPlanFailure: ((
            action: {
                type: 'delete rollout plan failure (products.featureFlags.rolloutPlanLogic.*)'
                payload: {
                    error: string
                    errorObject?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['products', 'featureFlags', 'rolloutPlanLogic', '*']
    pathString: 'products.featureFlags.rolloutPlanLogic.*'
    props: RolloutPlanLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        rolloutDraft: RolloutPlanMutationRequest
        planError: string | null
        rolloutPlan: RolloutPlan | null
        rolloutPlanLoading: boolean
    }
    reducers: {
        rolloutDraft: (state: RolloutPlanMutationRequest, action: any, fullState: any) => RolloutPlanMutationRequest
        planError: (state: string | null, action: any, fullState: any) => string | null
        rolloutPlan: (state: RolloutPlan | null, action: any, fullState: any) => RolloutPlan | null
        rolloutPlanLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        rolloutDraft: RolloutPlanMutationRequest
        planError: string | null
        rolloutPlan: RolloutPlan | null
        rolloutPlanLoading: boolean
    }
    selectors: {
        rolloutDraft: (state: any, props?: any) => RolloutPlanMutationRequest
        planError: (state: any, props?: any) => string | null
        rolloutPlan: (state: any, props?: any) => RolloutPlan | null
        rolloutPlanLoading: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        rolloutDraft: RolloutPlanMutationRequest
        planError: string | null
        rolloutPlan: RolloutPlan | null
        rolloutPlanLoading: boolean
    }
    _isKea: true
    _isKeaWithKey: true
}
