// Generated by kea-typegen. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { TraceLogicProps } from './traceLogic'
import type { EvaluationResult, TraceRequestRequest } from './generated/models/index'

export interface traceLogicType extends Logic {
    actionCreators: {
        setDistinctId: (distinctId: string) => {
            type: 'set distinct id (products.featureFlags.traceLogic.*)'
            payload: {
                distinctId: string
            }
        }
        setPropertiesText: (propertiesText: string) => {
            type: 'set properties text (products.featureFlags.traceLogic.*)'
            payload: {
                propertiesText: string
            }
        }
        submitTrace: () => {
            type: 'submit trace (products.featureFlags.traceLogic.*)'
            payload: {
                value: true
            }
        }
        setInputError: (inputError: string | null) => {
            type: 'set input error (products.featureFlags.traceLogic.*)'
            payload: {
                inputError: string | null
            }
        }
        setTraceError: (traceError: string | null) => {
            type: 'set trace error (products.featureFlags.traceLogic.*)'
            payload: {
                traceError: string | null
            }
        }
        runTrace: (request: TraceRequestRequest) => {
            type: 'run trace (products.featureFlags.traceLogic.*)'
            payload: TraceRequestRequest
        }
        runTraceSuccess: (
            traceResult: EvaluationResult,
            payload?: TraceRequestRequest
        ) => {
            type: 'run trace success (products.featureFlags.traceLogic.*)'
            payload: {
                traceResult: EvaluationResult
                payload?: TraceRequestRequest
            }
        }
        runTraceFailure: (
            error: string,
            errorObject?: any
        ) => {
            type: 'run trace failure (products.featureFlags.traceLogic.*)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'set distinct id (products.featureFlags.traceLogic.*)': 'setDistinctId'
        'set properties text (products.featureFlags.traceLogic.*)': 'setPropertiesText'
        'submit trace (products.featureFlags.traceLogic.*)': 'submitTrace'
        'set input error (products.featureFlags.traceLogic.*)': 'setInputError'
        'set trace error (products.featureFlags.traceLogic.*)': 'setTraceError'
        'run trace (products.featureFlags.traceLogic.*)': 'runTrace'
        'run trace success (products.featureFlags.traceLogic.*)': 'runTraceSuccess'
        'run trace failure (products.featureFlags.traceLogic.*)': 'runTraceFailure'
    }
    actionTypes: {
        setDistinctId: 'set distinct id (products.featureFlags.traceLogic.*)'
        setPropertiesText: 'set properties text (products.featureFlags.traceLogic.*)'
        submitTrace: 'submit trace (products.featureFlags.traceLogic.*)'
        setInputError: 'set input error (products.featureFlags.traceLogic.*)'
        setTraceError: 'set trace error (products.featureFlags.traceLogic.*)'
        runTrace: 'run trace (products.featureFlags.traceLogic.*)'
        runTraceSuccess: 'run trace success (products.featureFlags.traceLogic.*)'
        runTraceFailure: 'run trace failure (products.featureFlags.traceLogic.*)'
    }
    actions: {
        setDistinctId: (distinctId: string) => void
        setPropertiesText: (propertiesText: string) => void
        submitTrace: () => void
        setInputError: (inputError: string | null) => void
        setTraceError: (traceError: string | null) => void
        runTrace: (request: TraceRequestRequest) => void
        runTraceSuccess: (traceResult: EvaluationResult, payload?: TraceRequestRequest) => void
        runTraceFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        setDistinctId: (distinctId: string) => Promise<any>
        setPropertiesText: (propertiesText: string) => Promise<any>
        submitTrace: () => Promise<any>
        setInputError: (inputError: string | null) => Promise<any>
        setTraceError: (traceError: string | null) => Promise<any>
        runTrace: (request: TraceRequestRequest) => Promise<any>
        runTraceSuccess: (traceResult: EvaluationResult, payload?: TraceRequestRequest) => Promise<any>
        runTraceFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        distinctId: string
        propertiesText: string
        inputError: string | null
        traceError: string | null
        traceResult: EvaluationResult | null
        traceResultLoading: boolean
    }
    events: {}
    key: string
    listeners: {
        runTrace: ((
            action: {
                type: 'run trace (products.featureFlags.traceLogic.*)'
                payload: TraceRequestRequest
            },
            previousState: any
        ) => void | Promise<void>)[]
        runTraceFailure: ((
            action: {
                type: 'run trace failure (products.featureFlags.traceLogic.*)'
                payload: {
                    error: string
                    errorObject?: any
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
        submitTrace: ((
            action: {
                type: 'submit trace (products.featureFlags.traceLogic.*)'
                payload: {
                    value: true
                }
            },
            previousState: any
        ) => void | Promise<void>)[]
    }
    path: ['products', 'featureFlags', 'traceLogic', '*']
    pathString: 'products.featureFlags.traceLogic.*'
    props: TraceLogicProps
    reducer: (
        state: any,
        action: any,
        fullState: any
    ) => {
        distinctId: string
        propertiesText: string
        inputError: string | null
        traceError: string | null
        traceResult: EvaluationResult | null
        traceResultLoading: boolean
    }
    reducers: {
        distinctId: (state: string, action: any, fullState: any) => string
        propertiesText: (state: string, action: any, fullState: any) => string
        inputError: (state: string | null, action: any, fullState: any) => string | null
        traceError: (state: string | null, action: any, fullState: any) => string | null
        traceResult: (state: EvaluationResult | null, action: any, fullState: any) => EvaluationResult | null
        traceResultLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        distinctId: string
        propertiesText: string
        inputError: string | null
        traceError: string | null
        traceResult: EvaluationResult | null
        traceResultLoading: boolean
    }
    selectors: {
        distinctId: (state: any, props?: any) => string
        propertiesText: (state: any, props?: any) => string
        inputError: (state: any, props?: any) => string | null
        traceError: (state: any, props?: any) => string | null
        traceResult: (state: any, props?: any) => EvaluationResult | null
        traceResultLoading: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        distinctId: string
        propertiesText: string
        inputError: string | null
        traceError: string | null
        traceResult: EvaluationResult | null
        traceResultLoading: boolean
    }
    _isKea: true
    _isKeaWithKey: true
}
