# Generated by Django 5.2.17 on 2026-10-02 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import products.feature_flags.backend.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "api_token",
                    models.CharField(
                        default=products.feature_flags.backend.models.generate_public_api_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "secret_api_token",
                    models.CharField(
                        default=products.feature_flags.backend.models.unusable_secret_api_token,
                        editable=False,
                        max_length=128,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=400)),
                ("name", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("filters", models.JSONField(default=products.feature_flags.backend.models.default_filters)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="feature_flags.team",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [models.Index(fields=["team", "deleted"], name="feature_flags_team_deleted_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted", False)),
                        fields=("team", "key"),
                        name="feature_flags_unique_live_key_per_team",
                    )
                ],
            },
        ),
    ]
