# Generated by Django 5.2.17 on 2026-10-03 19:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_flags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolloutPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("HOLDING", "Holding"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("REVERTED", "Reverted"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("managed_group_index", models.PositiveIntegerField()),
                ("phases", models.JSONField()),
                ("current_phase_index", models.PositiveIntegerField(default=0)),
                ("phase_entered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("hold_reason", models.CharField(blank=True, max_length=100)),
                ("hold_started_at", models.DateTimeField(blank=True, null=True)),
                ("guardrail", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollout_plan",
                        to="feature_flags.featureflag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuardrailSample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("value", models.FloatField()),
                ("sample_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="feature_flags.rolloutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "-id"],
            },
        ),
    ]
