# Generated by Django 5.2.17 on 2026-10-04 14:12

import django.db.models.deletion
import products.feature_flags.backend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feature_flags", "0002_rolloutplan_guardrailsample"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rolloutplan",
            name="version",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.CreateModel(
            name="AutomationToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("selector", models.CharField(editable=False, max_length=22, unique=True)),
                ("secret_hash", models.CharField(editable=False, max_length=128)),
                (
                    "scopes",
                    models.JSONField(validators=[products.feature_flags.backend.models.validate_automation_scopes]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_tokens",
                        to="feature_flags.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
